jobs:
- job: Debug_Build
  pool: Hosted Ubuntu 1604
  steps:
    - template: templates/set-test-data-variables-step.yml
    - script: 'tools/ci_build/github/linux/hosting_run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x "--config Debug --build_hosting --use_openmp"'
      displayName: 'Debug Build'
    - template: templates/clean-agent-build-directory-step.yml
- job: Release_Build
  pool: Hosted Ubuntu 1604
  steps:
    - template: templates/set-test-data-variables-step.yml
    - script: 'tools/ci_build/github/linux/hosting_run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x "--config Release --build_hosting --use_openmp"'
      displayName: 'Release Build'
    - template: templates/clean-agent-build-directory-step.yml
